### ISSUE TITLE
Utilize OAuth Flow instead of Password Flow

### ISSUE THREAD

**Issue by adagioajanes** [coxlr/laravel-ringcentral#6]
Right now, the application requires a username and password to authenticate. I would like this to change to oauth flow so that the application logs in based on the context of the user accessing it.

I'm not sure all of the work that would be required to do this. But it would certainly improve the security of the middleware.

**Comment by 1337erik** [comment]
RingCentral is also going to be deprecating password auth soon

**Comment by coxlr** [comment]
Closing this for now as password auth has now been removed and replaced with JWT.  

I personally do not have the use case oauth flow currently, but would happily accept pull requests that implemented this along with associated tests. It may be something I add in the future if it is something I end up needed myself.
